/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RoomRoomIdRouteImport } from './routes/room.$roomId'
import { Route as ApiGameRoomsRouteImport } from './routes/api.game.rooms'
import { Route as ApiGameRoomsRoomIdRouteImport } from './routes/api.game.rooms.$roomId'
import { Route as ApiGameRoomsRoomIdActionRouteImport } from './routes/api.game.rooms.$roomId.action'
import { Route as ApiGameRoomsRoomIdAiGuessRouteImport } from './routes/api.game.rooms.$roomId.ai-guess'
import { Route as ApiGameRoomsRoomIdAiSessionRouteImport } from './routes/api.game.rooms.$roomId.ai-session'
import { Route as ApiGameRoomsRoomIdJoinRouteImport } from './routes/api.game.rooms.$roomId.join'
import { Route as ApiGameRoomsRoomIdLeaveRouteImport } from './routes/api.game.rooms.$roomId.leave'
import { Route as ApiGameRoomsRoomIdVerifyProofRouteImport } from './routes/api.game.rooms.$roomId.verify-proof'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameRoomsRoute = ApiGameRoomsRouteImport.update({
  id: '/api/game/rooms',
  path: '/api/game/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameRoomsRoomIdRoute = ApiGameRoomsRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => ApiGameRoomsRoute,
} as any)
const ApiGameRoomsRoomIdActionRoute =
  ApiGameRoomsRoomIdActionRouteImport.update({
    id: '/action',
    path: '/action',
    getParentRoute: () => ApiGameRoomsRoomIdRoute,
  } as any)
const ApiGameRoomsRoomIdAiGuessRoute =
  ApiGameRoomsRoomIdAiGuessRouteImport.update({
    id: '/ai-guess',
    path: '/ai-guess',
    getParentRoute: () => ApiGameRoomsRoomIdRoute,
  } as any)
const ApiGameRoomsRoomIdAiSessionRoute =
  ApiGameRoomsRoomIdAiSessionRouteImport.update({
    id: '/ai-session',
    path: '/ai-session',
    getParentRoute: () => ApiGameRoomsRoomIdRoute,
  } as any)
const ApiGameRoomsRoomIdJoinRoute = ApiGameRoomsRoomIdJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => ApiGameRoomsRoomIdRoute,
} as any)
const ApiGameRoomsRoomIdLeaveRoute = ApiGameRoomsRoomIdLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => ApiGameRoomsRoomIdRoute,
} as any)
const ApiGameRoomsRoomIdVerifyProofRoute =
  ApiGameRoomsRoomIdVerifyProofRouteImport.update({
    id: '/verify-proof',
    path: '/verify-proof',
    getParentRoute: () => ApiGameRoomsRoomIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/api/game/rooms': typeof ApiGameRoomsRouteWithChildren
  '/api/game/rooms/$roomId': typeof ApiGameRoomsRoomIdRouteWithChildren
  '/api/game/rooms/$roomId/action': typeof ApiGameRoomsRoomIdActionRoute
  '/api/game/rooms/$roomId/ai-guess': typeof ApiGameRoomsRoomIdAiGuessRoute
  '/api/game/rooms/$roomId/ai-session': typeof ApiGameRoomsRoomIdAiSessionRoute
  '/api/game/rooms/$roomId/join': typeof ApiGameRoomsRoomIdJoinRoute
  '/api/game/rooms/$roomId/leave': typeof ApiGameRoomsRoomIdLeaveRoute
  '/api/game/rooms/$roomId/verify-proof': typeof ApiGameRoomsRoomIdVerifyProofRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/api/game/rooms': typeof ApiGameRoomsRouteWithChildren
  '/api/game/rooms/$roomId': typeof ApiGameRoomsRoomIdRouteWithChildren
  '/api/game/rooms/$roomId/action': typeof ApiGameRoomsRoomIdActionRoute
  '/api/game/rooms/$roomId/ai-guess': typeof ApiGameRoomsRoomIdAiGuessRoute
  '/api/game/rooms/$roomId/ai-session': typeof ApiGameRoomsRoomIdAiSessionRoute
  '/api/game/rooms/$roomId/join': typeof ApiGameRoomsRoomIdJoinRoute
  '/api/game/rooms/$roomId/leave': typeof ApiGameRoomsRoomIdLeaveRoute
  '/api/game/rooms/$roomId/verify-proof': typeof ApiGameRoomsRoomIdVerifyProofRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/api/game/rooms': typeof ApiGameRoomsRouteWithChildren
  '/api/game/rooms/$roomId': typeof ApiGameRoomsRoomIdRouteWithChildren
  '/api/game/rooms/$roomId/action': typeof ApiGameRoomsRoomIdActionRoute
  '/api/game/rooms/$roomId/ai-guess': typeof ApiGameRoomsRoomIdAiGuessRoute
  '/api/game/rooms/$roomId/ai-session': typeof ApiGameRoomsRoomIdAiSessionRoute
  '/api/game/rooms/$roomId/join': typeof ApiGameRoomsRoomIdJoinRoute
  '/api/game/rooms/$roomId/leave': typeof ApiGameRoomsRoomIdLeaveRoute
  '/api/game/rooms/$roomId/verify-proof': typeof ApiGameRoomsRoomIdVerifyProofRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/room/$roomId'
    | '/api/game/rooms'
    | '/api/game/rooms/$roomId'
    | '/api/game/rooms/$roomId/action'
    | '/api/game/rooms/$roomId/ai-guess'
    | '/api/game/rooms/$roomId/ai-session'
    | '/api/game/rooms/$roomId/join'
    | '/api/game/rooms/$roomId/leave'
    | '/api/game/rooms/$roomId/verify-proof'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/room/$roomId'
    | '/api/game/rooms'
    | '/api/game/rooms/$roomId'
    | '/api/game/rooms/$roomId/action'
    | '/api/game/rooms/$roomId/ai-guess'
    | '/api/game/rooms/$roomId/ai-session'
    | '/api/game/rooms/$roomId/join'
    | '/api/game/rooms/$roomId/leave'
    | '/api/game/rooms/$roomId/verify-proof'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/terms'
    | '/room/$roomId'
    | '/api/game/rooms'
    | '/api/game/rooms/$roomId'
    | '/api/game/rooms/$roomId/action'
    | '/api/game/rooms/$roomId/ai-guess'
    | '/api/game/rooms/$roomId/ai-session'
    | '/api/game/rooms/$roomId/join'
    | '/api/game/rooms/$roomId/leave'
    | '/api/game/rooms/$roomId/verify-proof'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  ApiGameRoomsRoute: typeof ApiGameRoomsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/rooms': {
      id: '/api/game/rooms'
      path: '/api/game/rooms'
      fullPath: '/api/game/rooms'
      preLoaderRoute: typeof ApiGameRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/rooms/$roomId': {
      id: '/api/game/rooms/$roomId'
      path: '/$roomId'
      fullPath: '/api/game/rooms/$roomId'
      preLoaderRoute: typeof ApiGameRoomsRoomIdRouteImport
      parentRoute: typeof ApiGameRoomsRoute
    }
    '/api/game/rooms/$roomId/action': {
      id: '/api/game/rooms/$roomId/action'
      path: '/action'
      fullPath: '/api/game/rooms/$roomId/action'
      preLoaderRoute: typeof ApiGameRoomsRoomIdActionRouteImport
      parentRoute: typeof ApiGameRoomsRoomIdRoute
    }
    '/api/game/rooms/$roomId/ai-guess': {
      id: '/api/game/rooms/$roomId/ai-guess'
      path: '/ai-guess'
      fullPath: '/api/game/rooms/$roomId/ai-guess'
      preLoaderRoute: typeof ApiGameRoomsRoomIdAiGuessRouteImport
      parentRoute: typeof ApiGameRoomsRoomIdRoute
    }
    '/api/game/rooms/$roomId/ai-session': {
      id: '/api/game/rooms/$roomId/ai-session'
      path: '/ai-session'
      fullPath: '/api/game/rooms/$roomId/ai-session'
      preLoaderRoute: typeof ApiGameRoomsRoomIdAiSessionRouteImport
      parentRoute: typeof ApiGameRoomsRoomIdRoute
    }
    '/api/game/rooms/$roomId/join': {
      id: '/api/game/rooms/$roomId/join'
      path: '/join'
      fullPath: '/api/game/rooms/$roomId/join'
      preLoaderRoute: typeof ApiGameRoomsRoomIdJoinRouteImport
      parentRoute: typeof ApiGameRoomsRoomIdRoute
    }
    '/api/game/rooms/$roomId/leave': {
      id: '/api/game/rooms/$roomId/leave'
      path: '/leave'
      fullPath: '/api/game/rooms/$roomId/leave'
      preLoaderRoute: typeof ApiGameRoomsRoomIdLeaveRouteImport
      parentRoute: typeof ApiGameRoomsRoomIdRoute
    }
    '/api/game/rooms/$roomId/verify-proof': {
      id: '/api/game/rooms/$roomId/verify-proof'
      path: '/verify-proof'
      fullPath: '/api/game/rooms/$roomId/verify-proof'
      preLoaderRoute: typeof ApiGameRoomsRoomIdVerifyProofRouteImport
      parentRoute: typeof ApiGameRoomsRoomIdRoute
    }
  }
}

interface ApiGameRoomsRoomIdRouteChildren {
  ApiGameRoomsRoomIdActionRoute: typeof ApiGameRoomsRoomIdActionRoute
  ApiGameRoomsRoomIdAiGuessRoute: typeof ApiGameRoomsRoomIdAiGuessRoute
  ApiGameRoomsRoomIdAiSessionRoute: typeof ApiGameRoomsRoomIdAiSessionRoute
  ApiGameRoomsRoomIdJoinRoute: typeof ApiGameRoomsRoomIdJoinRoute
  ApiGameRoomsRoomIdLeaveRoute: typeof ApiGameRoomsRoomIdLeaveRoute
  ApiGameRoomsRoomIdVerifyProofRoute: typeof ApiGameRoomsRoomIdVerifyProofRoute
}

const ApiGameRoomsRoomIdRouteChildren: ApiGameRoomsRoomIdRouteChildren = {
  ApiGameRoomsRoomIdActionRoute: ApiGameRoomsRoomIdActionRoute,
  ApiGameRoomsRoomIdAiGuessRoute: ApiGameRoomsRoomIdAiGuessRoute,
  ApiGameRoomsRoomIdAiSessionRoute: ApiGameRoomsRoomIdAiSessionRoute,
  ApiGameRoomsRoomIdJoinRoute: ApiGameRoomsRoomIdJoinRoute,
  ApiGameRoomsRoomIdLeaveRoute: ApiGameRoomsRoomIdLeaveRoute,
  ApiGameRoomsRoomIdVerifyProofRoute: ApiGameRoomsRoomIdVerifyProofRoute,
}

const ApiGameRoomsRoomIdRouteWithChildren =
  ApiGameRoomsRoomIdRoute._addFileChildren(ApiGameRoomsRoomIdRouteChildren)

interface ApiGameRoomsRouteChildren {
  ApiGameRoomsRoomIdRoute: typeof ApiGameRoomsRoomIdRouteWithChildren
}

const ApiGameRoomsRouteChildren: ApiGameRoomsRouteChildren = {
  ApiGameRoomsRoomIdRoute: ApiGameRoomsRoomIdRouteWithChildren,
}

const ApiGameRoomsRouteWithChildren = ApiGameRoomsRoute._addFileChildren(
  ApiGameRoomsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
  ApiGameRoomsRoute: ApiGameRoomsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
